import ammoJson from "@/data/ammo.json";
import bossesJson from "@/data/bosses.json";
import enemiesJson from "@/data/enemies.json";
import metaJson from "@/data/meta.json";
import recipesJson from "@/data/recipes.json";
import weaponsJson from "@/data/weapons.json";
import { BIOME_ORDER } from "@/data/biomes";
import {
  WEAPON_CLASS_LABELS,
  WEAPON_CLASS_ORDER,
} from "@/data/weapon-class";
import type { Ammo, Creature, RecipeBook, Weapon } from "./types";

/** The datasets are generated by `npm run scrape` and committed, so the app
 *  never talks to the wiki at runtime. */
export const weapons = weaponsJson as unknown as Weapon[];
export const ammoItems = ammoJson as unknown as Ammo[];
/** The eight Forsaken, in ladder order. */
export const bosses = bossesJson as unknown as Creature[];
/** Hildir's minibosses and every regular aggressive creature. */
export const enemies = enemiesJson as unknown as Creature[];

/** Display order for the target picker: bosses, then minibosses, then regular
 *  enemies; within a kind, by how deep into the world you meet them. */
const KIND_ORDER: Record<Creature["kind"], number> = {
  boss: 0,
  miniboss: 1,
  enemy: 2,
};

/** Every selectable target, ready to render in one list. */
export const targets: Creature[] = [...bosses, ...enemies].sort(
  (a, b) =>
    KIND_ORDER[a.kind] - KIND_ORDER[b.kind] ||
    BIOME_ORDER[a.biome] - BIOME_ORDER[b.biome] ||
    a.name.localeCompare(b.name, "en"),
);

/** Crafting recipes by item slug, used for the upgrade-level gating. */
export const recipes = recipesJson as unknown as RecipeBook;

export const datasetMeta = metaJson as {
  generatedAt: string;
  source: string;
  sourceApi: string;
  counts: {
    weapons: number;
    ammo: number;
    bosses: number;
    minibosses?: number;
    enemies?: number;
    biomes?: number;
    recipes?: number;
  };
  availability?: string;
};

export const arrows = ammoItems.filter((a) => a.kind === "arrow");
export const bolts = ammoItems.filter((a) => a.kind === "bolt");

/** Group label + ordering used by the weapon filters. */
export const GROUP_LABELS: Record<Weapon["group"], string> = {
  melee: "Melee",
  ranged: "Ranged",
  magic: "Magic",
  consumable: "Thrown",
  siege: "Siege",
};

/** Order weapon classes from lightest to heaviest for grouped display. */
export const CLASS_ORDER = WEAPON_CLASS_ORDER;

export const CLASS_LABELS = WEAPON_CLASS_LABELS;
