// Builds standalone JS files from i18n JSON definitions for static web consumption.
// 1. shared/i18n/languages.json -> shared/i18n/languages.js (globalThis.VC_LANGUAGES)
// 2. apps/**/locales/messages.json -> apps/**/locales/messages.js (globalThis.VC_MESSAGES)

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SHARED_I18N_DIR = path.join(REPO_ROOT, 'shared', 'i18n');
const APPS_DIR = path.join(REPO_ROOT, 'apps');

function findLocales(dir) {
  const results = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (entry.name === 'locales') {
        const jsonPath = path.join(dir, 'locales', 'messages.json');
        if (existsSync(jsonPath)) results.push(path.join(dir, 'locales'));
      } else if (
        entry.name !== 'node_modules' &&
        entry.name !== 'dist' &&
        entry.name !== 'dist-static' &&
        !entry.name.startsWith('.')
      ) {
        results.push(...findLocales(path.join(dir, entry.name)));
      }
    }
  }
  return results;
}

export function buildI18n() {
  console.log('building i18n standalone files…');

  // 1. shared/i18n/languages.json -> shared/i18n/languages.js
  const languagesJsonPath = path.join(SHARED_I18N_DIR, 'languages.json');
  if (existsSync(languagesJsonPath)) {
    const rawLanguages = readFileSync(languagesJsonPath, 'utf8');
    const languages = JSON.parse(rawLanguages);
    const languagesJs = `// Generated by scripts/build-i18n.mjs — DO NOT EDIT MANUALLY\nglobalThis.VC_LANGUAGES = ${JSON.stringify(languages, null, 2)};\n`;
    const languagesJsPath = path.join(SHARED_I18N_DIR, 'languages.js');
    writeFileSync(languagesJsPath, languagesJs, 'utf8');
    console.log(`  -> wrote ${path.relative(REPO_ROOT, languagesJsPath)}`);
  } else {
    console.warn(`  ! warning: ${languagesJsonPath} not found`);
  }

  // 2. apps/**/locales/messages.json -> apps/**/locales/messages.js
  const localesDirs = findLocales(APPS_DIR);
  for (const localesDir of localesDirs) {
    const messagesJsonPath = path.join(localesDir, 'messages.json');
    if (existsSync(messagesJsonPath)) {
      const rawMessages = readFileSync(messagesJsonPath, 'utf8');
      const messages = JSON.parse(rawMessages);
      const messagesJs = `// Generated by scripts/build-i18n.mjs — DO NOT EDIT MANUALLY\nglobalThis.VC_MESSAGES = ${JSON.stringify(messages, null, 2)};\n`;
      const messagesJsPath = path.join(localesDir, 'messages.js');
      writeFileSync(messagesJsPath, messagesJs, 'utf8');
      console.log(`  -> wrote ${path.relative(REPO_ROOT, messagesJsPath)}`);
    }
  }

  console.log('done: i18n build complete');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  buildI18n();
}
