// Generated by scripts/build-i18n.mjs — DO NOT EDIT MANUALLY
globalThis.VC_MESSAGES = {
  "← Valheim Companion": {
    "en": "← Valheim Companion",
    "cs": "← Valheim Companion",
    "de": "← Valheim Companion",
    "es": "← Valheim Companion",
    "fr": "← Valheim Companion",
    "pt": "← Valheim Companion",
    "zh": "← Valheim Companion",
    "hi": "← Valheim Companion",
    "ar": "← Valheim Companion",
    "bn": "← Valheim Companion",
    "ru": "← Valheim Companion",
    "ja": "← Valheim Companion",
    "id": "← Valheim Companion"
  },
  "Trader Ledger": {
    "en": "Trader Ledger",
    "cs": "Trader Ledger",
    "de": "Trader Ledger",
    "es": "Trader Ledger",
    "fr": "Trader Ledger",
    "pt": "Trader Ledger",
    "zh": "Trader Ledger",
    "hi": "Trader Ledger",
    "ar": "Trader Ledger",
    "bn": "Trader Ledger",
    "ru": "Trader Ledger",
    "ja": "Trader Ledger",
    "id": "Trader Ledger"
  },
  "Merchandise catalog, unlock requirements, and treasure appraisal for Haldor, Hildir & The Bog Witch.": {
    "en": "Merchandise catalog, unlock requirements, and treasure appraisal for Haldor, Hildir & The Bog Witch.",
    "cs": "Katalog zboží, podmínky odemknutí a kalkulačka pokladů pro Haldora, Hildir a Bog Witch.",
    "de": "Warenkatalog, Freischaltbedingungen und Schatzschätzung für Haldor, Hildir & Die Moorhexe.",
    "es": "Catálogo de mercancías, requisitos de desbloqueo y tasación de tesoros para Haldor, Hildir y La Bruja del Pantano.",
    "fr": "Catalogue de marchandises, conditions de déblocage et estimation de trésor pour Haldor, Hildir & La Sorcière des Marais.",
    "pt": "Catálogo de mercadorias, requisitos de desbloqueio e avaliação de tesouros para Haldor, Hildir e A Bruxa do Pântano.",
    "zh": "哈尔多、希尔迪尔与沼泽女巫的商品目录、解锁条件与宝物估价。",
    "hi": "हाल्डोर, हिल्दिर और बॉग विच के लिए माल सूची, अनलॉक शर्तें और खजाना मूल्यांकन।",
    "ar": "كتالوج البضائع وشروط الفتح وتقييم الكنوز لهالدور، وهيلدير، وساحرة المستنقع.",
    "bn": "হ্যালডোর, হিলদির এবং বগ উইচের জন্য পণ্যের ক্যাটালগ, আনলক শর্ত এবং ট্রেজার মূল্যায়ন।",
    "ru": "Каталог товаров, условия разблокировки и оценка сокровищ для Хальдора, Хильдир и Болотной ведьмы.",
    "ja": "ハルドール、ヒルディル、沼の魔女の取扱商品カタログ、解放条件、お宝鑑定。",
    "id": "Katalog barang dagangan, syarat pembuka kunci, dan penilaian harta untuk Haldor, Hildir & The Bog Witch."
  },
  "Track your progress →": {
    "en": "Track your progress →",
    "cs": "Sledujte svůj postup →",
    "de": "Fortschritt verfolgen →",
    "es": "Registra tu progreso →",
    "fr": "Suivez votre progression →",
    "pt": "Acompanhe seu progresso →",
    "zh": "记录你的进度 →",
    "hi": "अपनी प्रगति दर्ज करें →",
    "ar": "تتبّع تقدمك →",
    "bn": "আপনার অগ্রগতি নথিভুক্ত করুন →",
    "ru": "Отслеживайте прогресс →",
    "ja": "進行状況を記録 →",
    "id": "Catat progresmu →"
  },
  "Treasure Appraisal": {
    "en": "Treasure Appraisal",
    "cs": "Kalkulačka pokladů",
    "de": "Schatzschätzung",
    "es": "Tasación de tesoros",
    "fr": "Estimation de trésor",
    "pt": "Avaliação de tesouros",
    "zh": "宝物估价",
    "hi": "खजाना मूल्यांकन",
    "ar": "تقييم الكنوز",
    "bn": "ট্রেজার মূল্যায়ন",
    "ru": "Оценка сокровищ",
    "ja": "お宝鑑定",
    "id": "Penilaian Harta"
  },
  "Calculate your coins and valuables appraisal to see what you can afford.": {
    "en": "Calculate your coins and valuables appraisal to see what you can afford.",
    "cs": "Spočítejte své mince a hodnotu cenností, abyste viděli, co si můžete dovolit.",
    "de": "Berechnen Sie Ihre Münzen und Schätze, um zu sehen, was Sie sich leisten können.",
    "es": "Calcula tus monedas y el valor de tus tesoros para ver qué puedes comprar.",
    "fr": "Calculez vos pièces et l'estimation de vos objets précieux pour voir ce que vous pouvez vous offrir.",
    "pt": "Calcule suas moedas e o valor de seus itens preciosos para ver o que pode comprar.",
    "zh": "计算你的硬币和贵重物品总值，看看你能买得起什么。",
    "hi": "अपने सिक्के और कीमती सामान का मूल्यांकन करें ताकि जान सकें कि आप क्या खरीद सकते हैं।",
    "ar": "احسب رصيدك من العملات وقيمة مقتنياتك الثمينة لتعرف ما يمكنك شراؤه.",
    "bn": "আপনার কয়েন এবং মূল্যবান জিনিসপত্রের মোট হিসাব করুন এবং দেখুন আপনি কী কিনতে পারবেন।",
    "ru": "Подсчитайте монеты и стоимость ценностей, чтобы узнать, что вы можете себе позволить.",
    "ja": "所持コインと換金アイテムの合計額を計算し、購入できる商品を確認します。",
    "id": "Hitung koin dan nilai barang berhargamu untuk melihat apa yang bisa dibeli."
  },
  "Coins": {
    "en": "Coins",
    "cs": "Mince",
    "de": "Münzen",
    "es": "Monedas",
    "fr": "Pièces",
    "pt": "Moedas",
    "zh": "硬币",
    "hi": "सिक्के",
    "ar": "عملات",
    "bn": "কয়েন",
    "ru": "Монеты",
    "ja": "コイン",
    "id": "Koin"
  },
  "Amber (5 coins)": {
    "en": "Amber (5 coins)",
    "cs": "Jantar (5 mincí)",
    "de": "Bernstein (5 Münzen)",
    "es": "Ámbar (5 monedas)",
    "fr": "Ambre (5 pièces)",
    "pt": "Âmbar (5 moedas)",
    "zh": "琥珀（5 枚硬币）",
    "hi": "अंबर (5 सिक्के)",
    "ar": "كهرمان (5 عملات)",
    "bn": "অ্যাম্বার (৫টি মুদ্রা)",
    "ru": "Янтарь (5 монет)",
    "ja": "琥珀（5 コイン）",
    "id": "Amber (5 koin)"
  },
  "Amber Pearl (10 coins)": {
    "en": "Amber Pearl (10 coins)",
    "cs": "Jantarová perla (10 mincí)",
    "de": "Bernsteinperle (10 Münzen)",
    "es": "Perla de ámbar (10 monedas)",
    "fr": "Perle d'ambre (10 pièces)",
    "pt": "Pérola de âmbar (10 moedas)",
    "zh": "琥珀珍珠（10 枚硬币）",
    "hi": "अंबर मोती (10 सिक्के)",
    "ar": "لؤلؤة الكهرمان (10 عملات)",
    "bn": "অ্যাম্বার মুক্তা (১০টি মুদ্রা)",
    "ru": "Янтарная жемчужина (10 монет)",
    "ja": "琥珀の真珠（10 コイン）",
    "id": "Mutiara Amber (10 koin)"
  },
  "Ruby (20 coins)": {
    "en": "Ruby (20 coins)",
    "cs": "Rubín (20 mincí)",
    "de": "Rubin (20 Münzen)",
    "es": "Rubí (20 monedas)",
    "fr": "Rubis (20 pièces)",
    "pt": "Rubi (20 moedas)",
    "zh": "红宝石（20 枚硬币）",
    "hi": "माणिक (20 सिक्के)",
    "ar": "ياقوت (20 عملة)",
    "bn": "রুবি (২০টি মুদ্রা)",
    "ru": "Рубин (20 монет)",
    "ja": "ルビー（20 コイン）",
    "id": "Rubi (20 koin)"
  },
  "Silver Necklace (30 coins)": {
    "en": "Silver Necklace (30 coins)",
    "cs": "Stříbrný náhrdelník (30 mincí)",
    "de": "Silberkette (30 Münzen)",
    "es": "Collar de plata (30 monedas)",
    "fr": "Collier en argent (30 pièces)",
    "pt": "Colar de prata (30 moedas)",
    "zh": "银项链（30 枚硬币）",
    "hi": "चांदी का हार (30 सिक्के)",
    "ar": "قلادة فضية (30 عملة)",
    "bn": "রুপোর নেকলেস (৩০টি মুদ্রা)",
    "ru": "Серебряное ожерелье (30 монет)",
    "ja": "銀の首飾り（30 コイン）",
    "id": "Kalung Perak (30 koin)"
  },
  "Total appraisal": {
    "en": "Total appraisal",
    "cs": "Celkové jmění",
    "de": "Gesamtwert",
    "es": "Tasación total",
    "fr": "Valeur totale",
    "pt": "Avaliação total",
    "zh": "估价总计",
    "hi": "कुल मूल्यांकन",
    "ar": "إجمالي القيمة",
    "bn": "মোট মূল্যায়ন",
    "ru": "Общее состояние",
    "ja": "合計鑑定額",
    "id": "Total Penilaian"
  },
  "From valuables": {
    "en": "From valuables",
    "cs": "Z cenností",
    "de": "Aus Wertsachen",
    "es": "De objetos de valor",
    "fr": "Objets précieux",
    "pt": "De objetos de valor",
    "zh": "来自贵重物品",
    "hi": "कीमती सामान से",
    "ar": "من المقتنيات الثمينة",
    "bn": "মূল্যবান জিনিস থেকে",
    "ru": "Из ценностей",
    "ja": "換金アイテム分",
    "id": "Dari barang berharga"
  },
  "Affordable": {
    "en": "Affordable",
    "cs": "Dostupné",
    "de": "Erschwinglich",
    "es": "Asequible",
    "fr": "Abordable",
    "pt": "Acessível",
    "zh": "买得起",
    "hi": "उपलब्ध",
    "ar": "في المتناول",
    "bn": "সাশ্রয়ী",
    "ru": "Доступно",
    "ja": "購入可能",
    "id": "Terjangkau"
  },
  "Locked": {
    "en": "Locked",
    "cs": "Zamčeno",
    "de": "Gesperrt",
    "es": "Bloqueado",
    "fr": "Verrouillé",
    "pt": "Bloqueado",
    "zh": "未解锁",
    "hi": "बंद",
    "ar": "مقفل",
    "bn": "লক করা",
    "ru": "Закрыто",
    "ja": "未解放",
    "id": "Terkunci"
  },
  "Reveal": {
    "en": "Reveal",
    "cs": "Odhalit",
    "de": "Enthüllen",
    "es": "Revelar",
    "fr": "Révéler",
    "pt": "Revelar",
    "zh": "揭示",
    "hi": "दिखाएँ",
    "ar": "كشف",
    "bn": "প্রকাশ করুন",
    "ru": "Показать",
    "ja": "表示",
    "id": "Ungkap"
  },
  "Close": {
    "en": "Close",
    "cs": "Zavřít",
    "de": "Schließen",
    "es": "Cerrar",
    "fr": "Fermer",
    "pt": "Fechar",
    "zh": "关闭",
    "hi": "बंद करें",
    "ar": "إغلاق",
    "bn": "বন্ধ করুন",
    "ru": "Закрыть",
    "ja": "閉じる",
    "id": "Tutup"
  },
  "Add to shopping cart": {
    "en": "Add to shopping cart",
    "cs": "Přidat do nákupního košíku",
    "de": "In den Einkaufswagen",
    "es": "Añadir a la cesta",
    "fr": "Ajouter au panier",
    "pt": "Adicionar ao carrinho",
    "zh": "加入购物车",
    "hi": "कार्ट में जोड़ें",
    "ar": "أضف إلى السلة",
    "bn": "কার্টে যোগ করুন",
    "ru": "В корзину",
    "ja": "カートに追加",
    "id": "Tambah ke keranjang"
  },
  "View in Items Compendium →": {
    "en": "View in Items Compendium →",
    "cs": "Zobrazit v Items Compendium →",
    "de": "Im Items Compendium ansehen →",
    "es": "Ver en Items Compendium →",
    "fr": "Voir dans l'Items Compendium →",
    "pt": "Ver no Items Compendium →",
    "zh": "在物品图鉴中查看 →",
    "hi": "Items Compendium में देखें →",
    "ar": "عرض في دليل العناصر →",
    "bn": "Items Compendium এ দেখুন →",
    "ru": "Смотреть в Items Compendium →",
    "ja": "Items Compendium で確認 →",
    "id": "Lihat di Items Compendium →"
  },
  "How to find:": {
    "en": "How to find:",
    "cs": "Jak najít:",
    "de": "Fundort:",
    "es": "Cómo encontrar:",
    "fr": "Comment le trouver :",
    "pt": "Como encontrar:",
    "zh": "如何找到：",
    "hi": "कैसे खोजें:",
    "ar": "كيفية العثور عليه:",
    "bn": "কীভাবে খুঁজে পাবেন:",
    "ru": "Как найти:",
    "ja": "見つけ方：",
    "id": "Cara menemukan:"
  },
  "Clear appraisal": {
    "en": "Clear appraisal",
    "cs": "Vymazat kalkulačku",
    "de": "Berechnung löschen",
    "es": "Borrar tasación",
    "fr": "Effacer l'estimation",
    "pt": "Limpar avaliação",
    "zh": "清除估价",
    "hi": "मूल्यांकन साफ़ करें",
    "ar": "مسح التقييم",
    "bn": "হিসাব মুছুন",
    "ru": "Сбросить расчет",
    "ja": "鑑定をクリア",
    "id": "Hapus penilaian"
  },
  "Language": {
    "en": "Language",
    "cs": "Jazyk",
    "de": "Sprache",
    "es": "Idioma",
    "fr": "Langue",
    "pt": "Idioma",
    "zh": "语言",
    "hi": "भाषा",
    "ar": "اللغة",
    "bn": "ভাষা",
    "ru": "Язык",
    "ja": "言語",
    "id": "Bahasa"
  },
  "Auto (browser)": {
    "en": "Auto (browser)",
    "cs": "Automaticky (prohlížeč)",
    "de": "Automatisch (Browser)",
    "es": "Automático (navegador)",
    "fr": "Automatique (navigateur)",
    "pt": "Automático (navegador)",
    "zh": "自动（浏览器）",
    "hi": "स्वचालित (ब्राउज़र)",
    "ar": "تلقائي (المتصفح)",
    "bn": "স্বয়ংক্রিয় (ব্রাউজার)",
    "ru": "Автоматически (браузер)",
    "ja": "自動（ブラウザ）",
    "id": "Otomatis (peramban)"
  },
  "Free, ad-free and made in my spare time.": {
    "en": "Free, ad-free and made in my spare time.",
    "cs": "Zdarma, bez reklam a tvořené ve volném čase.",
    "de": "Kostenlos, werbefrei und in meiner Freizeit erstellt.",
    "es": "Gratis, sin publicidad y hecho en mi tiempo libre.",
    "fr": "Gratuit, sans publicité et créé sur mon temps libre.",
    "pt": "Gratuito, sem anúncios e feito no meu tempo livre.",
    "zh": "免费、无广告，并在我的业余时间制作。",
    "hi": "निःशुल्क, विज्ञापन-मुक्त और मेरे खाली समय में निर्मित।",
    "ar": "مجاني، خالي من الإعلانات ومصنوع في وقت فراغي.",
    "bn": "বিনামূল্যে, বিজ্ঞাপনহীন এবং আমার অবসর সময়ে তৈরি।",
    "ru": "Бесплатно, без рекламы и сделано в свободное время.",
    "ja": "無料、広告なし、個人の余暇で制作されています。",
    "id": "Gratis, bebas iklan, dan dibuat di waktu luang saya."
  },
  "If it helped your run, you can buy me a coffee.": {
    "en": "If it helped your run, you can buy me a coffee.",
    "cs": "Pokud vám pomohl při hraní, můžete mi koupit kávu.",
    "de": "Wenn es Ihnen geholfen hat, können Sie mir einen Kaffee spendieren.",
    "es": "Si te ayudó en tu partida, puedes invitarme a un café.",
    "fr": "Si cela vous a aidé dans votre partie, vous pouvez m'offrir un café.",
    "pt": "Se isso ajudou em seu jogo, você pode me pagar um café.",
    "zh": "如果这对你的冒险有所帮助，可以请我喝杯咖啡。",
    "hi": "अगर इससे आपके खेल में मदद मिली, तो आप मुझे एक कॉफी खरीद सकते हैं।",
    "ar": "إذا كان قد ساعدك في رحلتك، يمكنك شراء فنجان قهوة لي.",
    "bn": "এটি যদি আপনার গেমে সাহায্য করে থাকে, তবে আপনি আমাকে একটি কফি কিনে দিতে পারেন।",
    "ru": "Если сайт помог вам в игре, вы можете угостить меня кофе.",
    "ja": "冒険の役に立ったら、コーヒーを一杯奢っていただけると嬉しいです。",
    "id": "Jika ini membantu petualanganmu, kamu bisa membelikan saya kopi."
  },
  "Buy Me a Coffee at ko-fi.com": {
    "en": "Buy Me a Coffee at ko-fi.com",
    "cs": "Koupit kávu na ko-fi.com",
    "de": "Kauf mir einen Kaffee auf ko-fi.com",
    "es": "Cómprame un café en ko-fi.com",
    "fr": "Offrez-moi un café sur ko-fi.com",
    "pt": "Pague-me um café no ko-fi.com",
    "zh": "在 ko-fi.com 请我喝杯咖啡",
    "hi": "ko-fi.com पर मुझे एक कॉफ़ी खरीदें",
    "ar": "اشترِ لي قهوة على ko-fi.com",
    "bn": "ko-fi.com-এ আমাকে একটি কফি কিনুন",
    "ru": "Купите мне кофе на ko-fi.com",
    "ja": "ko-fi.com でコーヒーを支援する",
    "id": "Traktir saya kopi di ko-fi.com"
  },
  "Fan project, not affiliated with Iron Gate. Data: Valheim Wiki (CC BY-SA 4.0).": {
    "en": "Fan project, not affiliated with Iron Gate. Data: Valheim Wiki (CC BY-SA 4.0).",
    "cs": "Fanouškovský projekt, není spojen s Iron Gate. Data: Valheim Wiki (CC BY-SA 4.0).",
    "de": "Fanprojekt, nicht mit Iron Gate verbunden. Daten: Valheim Wiki (CC BY-SA 4.0).",
    "es": "Proyecto de fans, no afiliado a Iron Gate. Datos: Valheim Wiki (CC BY-SA 4.0).",
    "fr": "Projet de fans, non affilié à Iron Gate. Données : Valheim Wiki (CC BY-SA 4.0).",
    "pt": "Projeto de fãs, não afiliado à Iron Gate. Dados: Valheim Wiki (CC BY-SA 4.0).",
    "zh": "粉丝项目，与 Iron Gate 无关。数据来源：Valheim Wiki (CC BY-SA 4.0)。",
    "hi": "प्रशंसक परियोजना, Iron Gate से संबद्ध नहीं। डेटा: Valheim Wiki (CC BY-SA 4.0)।",
    "ar": "مشروع من المعجبين، غير تابع لـ Iron Gate. البيانات: Valheim Wiki (CC BY-SA 4.0).",
    "bn": "ফ্যান প্রকল্প, Iron Gate এর সাথে অনুমোদিত নয়। ডেটা: Valheim Wiki (CC BY-SA 4.0)।",
    "ru": "Фанатский проект, не связан с Iron Gate. Данные: Valheim Wiki (CC BY-SA 4.0).",
    "ja": "ファンプロジェクトであり、Iron Gate とは提携していません。データ：Valheim Wiki (CC BY-SA 4.0)。",
    "id": "Proyek penggemar, tidak berafiliasi dengan Iron Gate. Data: Valheim Wiki (CC BY-SA 4.0)."
  },
  "{count} coins": {
    "en": {
      "one": "{count} coin",
      "other": "{count} coins"
    },
    "cs": {
      "one": "{count} mince",
      "few": "{count} mince",
      "many": "{count} mince",
      "other": "{count} mincí"
    },
    "de": {
      "one": "{count} Münze",
      "other": "{count} Münzen"
    },
    "es": {
      "one": "{count} moneda",
      "many": "{count} monedas",
      "other": "{count} monedas"
    },
    "fr": {
      "one": "{count} pièce",
      "many": "{count} pièces",
      "other": "{count} pièces"
    },
    "pt": {
      "one": "{count} moeda",
      "many": "{count} moedas",
      "other": "{count} moedas"
    },
    "zh": {
      "other": "{count} 枚硬币"
    },
    "hi": {
      "one": "{count} सिक्का",
      "other": "{count} सिक्के"
    },
    "ar": {
      "zero": "{count} عملات",
      "one": "{count} عملة",
      "two": "{count} عملتان",
      "few": "{count} عملات",
      "many": "{count} عملة",
      "other": "{count} عملة"
    },
    "bn": {
      "one": "{count}টি মুদ্রা",
      "other": "{count}টি মুদ্রা"
    },
    "ru": {
      "one": "{count} монета",
      "few": "{count} монеты",
      "many": "{count} монет",
      "other": "{count} монеты"
    },
    "ja": {
      "other": "{count} コイン"
    },
    "id": {
      "other": "{count} koin"
    }
  },
  "{count} affordable": {
    "en": {
      "one": "{count} affordable",
      "other": "{count} affordable"
    },
    "cs": {
      "one": "{count} dostupné",
      "few": "{count} dostupná",
      "many": "{count} dostupných",
      "other": "{count} dostupných"
    },
    "de": {
      "one": "{count} erschwinglich",
      "other": "{count} erschwinglich"
    },
    "es": {
      "one": "{count} asequible",
      "many": "{count} asequibles",
      "other": "{count} asequibles"
    },
    "fr": {
      "one": "{count} abordable",
      "many": "{count} abordables",
      "other": "{count} abordables"
    },
    "pt": {
      "one": "{count} acessível",
      "many": "{count} acessíveis",
      "other": "{count} acessíveis"
    },
    "zh": {
      "other": "{count} 件买得起"
    },
    "hi": {
      "one": "{count} खरीदने योग्य",
      "other": "{count} खरीदने योग्य"
    },
    "ar": {
      "zero": "{count} في متناول اليد",
      "one": "{count} في متناول اليد",
      "two": "{count} في متناول اليد",
      "few": "{count} في متناول اليد",
      "many": "{count} في متناول اليد",
      "other": "{count} في متناول اليد"
    },
    "bn": {
      "one": "{count}টি সাশ্রয়ী",
      "other": "{count}টি সাশ্রয়ী"
    },
    "ru": {
      "one": "{count} доступно",
      "few": "{count} доступны",
      "many": "{count} доступно",
      "other": "{count} доступно"
    },
    "ja": {
      "other": "{count} 個購入可能"
    },
    "id": {
      "other": "{count} terjangkau"
    }
  },
  "In cart": {
    "en": "In cart",
    "cs": "V košíku",
    "de": "Im Einkaufswagen",
    "es": "En la cesta",
    "fr": "Dans le panier",
    "pt": "No carrinho",
    "zh": "已在购物车",
    "hi": "कार्ट में",
    "ar": "في السلة",
    "bn": "কার্টে",
    "ru": "В корзине",
    "ja": "カート内",
    "id": "Di keranjang"
  },
  "Added to shopping cart.": {
    "en": "Added to shopping cart.",
    "cs": "Přidáno do nákupního košíku.",
    "de": "In den Einkaufswagen gelegt.",
    "es": "Añadido a la cesta.",
    "fr": "Ajouté au panier.",
    "pt": "Adicionado ao carrinho.",
    "zh": "已加入购物车。",
    "hi": "शॉपिंग कार्ट में जोड़ा गया।",
    "ar": "تمت الإضافة إلى سلة التسوق.",
    "bn": "শপিং কার্টে যোগ করা হয়েছে।",
    "ru": "Добавлено в корзину.",
    "ja": "ショッピングカートに追加しました。",
    "id": "Ditambahkan ke keranjang belanja."
  },
  "Show only affordable": {
    "en": "Show only affordable",
    "cs": "Pouze dostupné zboží",
    "de": "Nur bezahlbare Artikel",
    "es": "Solo asequibles",
    "fr": "Articles abordables uniquement",
    "pt": "Apenas acessíveis",
    "zh": "仅显示买得起的",
    "hi": "केवल वहन करने योग्य दिखाएं",
    "ar": "إظهار البضائع المتاحة فقط",
    "bn": "কেবল সাশ্রয়ী পণ্য দেখান",
    "ru": "Только доступные товары",
    "ja": "購入可能のみ表示",
    "id": "Tampilkan yang terjangkau saja"
  },
  "Showing only affordable": {
    "en": "Showing only affordable",
    "cs": "Zobrazeno pouze dostupné",
    "de": "Nur bezahlbare angezeigt",
    "es": "Mostrando solo asequibles",
    "fr": "Affichage des abordables uniquement",
    "pt": "Mostrando apenas acessíveis",
    "zh": "正在显示买得起的商品",
    "hi": "केवल वहन करने योग्य दिखाए जा रहे हैं",
    "ar": "يتم عرض البضائع المتاحة فقط",
    "bn": "কেবল সাশ্রয়ী পণ্য প্রদর্শিত হচ্ছে",
    "ru": "Показаны только доступные",
    "ja": "購入可能のみ表示中",
    "id": "Menampilkan yang terjangkau saja"
  },
  "Collapse calculator": {
    "en": "Collapse calculator",
    "cs": "Sbalit kalkulačku",
    "de": "Rechner einklappen",
    "es": "Plegar calculadora",
    "fr": "Réduire la calculatrice",
    "pt": "Recolher calculadora",
    "zh": "折叠估价计算器",
    "hi": "कैलकुलेटर संक्षिप्त करें",
    "ar": "طي الآلة الحاسبة",
    "bn": "ক্যালকুলেটর সংকোচন করুন",
    "ru": "Свернуть калькулятор",
    "ja": "計算ツールを折りたたむ",
    "id": "Ciutkan kalkulator"
  },
  "Expand calculator": {
    "en": "Expand calculator",
    "cs": "Rozbalit kalkulačku",
    "de": "Rechner ausklappen",
    "es": "Desplegar calculadora",
    "fr": "Développer la calculatrice",
    "pt": "Expandir calculadora",
    "zh": "展开估价计算器",
    "hi": "कैलकुलेटर विस्तृत करें",
    "ar": "توسيع الآلة الحاسبة",
    "bn": "ক্যালকুলেটর প্রসারিত করুন",
    "ru": "Развернуть калькулятор",
    "ja": "計算ツールを展開",
    "id": "Perluas kalkulator"
  },
  "Boss preparation: {boss} →": {
    "en": "Boss preparation: {boss} →",
    "cs": "Příprava na bosse: {boss} →",
    "de": "Boss-Vorbereitung: {boss} →",
    "es": "Preparación para jefe: {boss} →",
    "fr": "Préparation du boss : {boss} →",
    "pt": "Preparação para o chefe: {boss} →",
    "zh": "Boss准备攻略：{boss} →",
    "hi": "बॉस तैयारी: {boss} →",
    "ar": "الاستعداد للزعيم: {boss} →",
    "bn": "বস প্রস্তুতি: {boss} →",
    "ru": "Подготовка к боссу: {boss} →",
    "ja": "ボス攻略準備: {boss} →",
    "id": "Persiapan boss: {boss} →"
  },
  "No affordable items with current coins.": {
    "en": "No affordable items with current coins.",
    "cs": "Za aktuální mince nelze koupit žádné zboží.",
    "de": "Keine bezahlbaren Artikel mit aktuellen Münzen.",
    "es": "No hay artículos asequibles con las monedas actuales.",
    "fr": "Aucun article abordable avec les pièces actuelles.",
    "pt": "Nenhum item acessível com as moedas atuais.",
    "zh": "当前硬币数量不足以购买任何商品。",
    "hi": "वर्तमान सिक्कों से कोई वस्तु खरीदने योग्य नहीं है।",
    "ar": "لا توجد بضائع ميسورة التكلفة بالعملات الحالية.",
    "bn": "বর্তমান কয়েন দিয়ে কোনো সাশ্রয়ী পণ্য নেই।",
    "ru": "Нет доступных товаров на текущее количество монет.",
    "ja": "現在のコインで購入できる商品はありません。",
    "id": "Tidak ada barang yang terjangkau dengan koin saat ini."
  },
  "x{count}": {
    "en": {
      "one": "×{count}",
      "other": "×{count}"
    },
    "cs": {
      "one": "×{count}",
      "few": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "de": {
      "one": "×{count}",
      "other": "×{count}"
    },
    "es": {
      "one": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "fr": {
      "one": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "pt": {
      "one": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "zh": {
      "other": "×{count}"
    },
    "hi": {
      "one": "×{count}",
      "other": "×{count}"
    },
    "ar": {
      "zero": "×{count}",
      "one": "×{count}",
      "two": "×{count}",
      "few": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "bn": {
      "one": "×{count}",
      "other": "×{count}"
    },
    "ru": {
      "one": "×{count}",
      "few": "×{count}",
      "many": "×{count}",
      "other": "×{count}"
    },
    "ja": {
      "other": "×{count}"
    },
    "id": {
      "other": "×{count}"
    }
  },
  "Requires defeating {boss}": {
    "en": "Requires defeating {boss}",
    "cs": "Vyžaduje porazit: {boss}",
    "de": "Erfordert den Sieg über {boss}",
    "es": "Requiere derrotar a {boss}",
    "fr": "Nécessite de vaincre {boss}",
    "pt": "Requer derrotar {boss}",
    "zh": "需要击败 {boss}",
    "hi": "{boss} को हराना आवश्यक है",
    "ar": "يتطلب هزيمة {boss}",
    "bn": "{boss} কে পরাজিত করতে হবে",
    "ru": "Требуется победить: {boss}",
    "ja": "{boss}を倒す必要があります",
    "id": "Perlu mengalahkan {boss}"
  },
  "Requires progress in a later biome": {
    "en": "Requires progress in a later biome",
    "cs": "Vyžaduje postup v pozdějším biomu",
    "de": "Erfordert Fortschritt in einem späteren Biom",
    "es": "Requiere avanzar en un bioma posterior",
    "fr": "Nécessite de progresser dans un biome ultérieur",
    "pt": "Requer progresso em um bioma posterior",
    "zh": "需要在后续生物群系中取得进展",
    "hi": "आगे के बायोम में प्रगति आवश्यक है",
    "ar": "يتطلب التقدم في منطقة حيوية لاحقة",
    "bn": "পরবর্তী বায়োমে অগ্রগতি প্রয়োজন",
    "ru": "Требуется прогресс в более позднем биоме",
    "ja": "後のバイオームで進行する必要があります",
    "id": "Memerlukan kemajuan di bioma berikutnya"
  },
  "Requires returning Hildir's {chest} chest ({boss})": {
    "en": "Requires returning Hildir's {chest} chest ({boss})",
    "cs": "Vyžaduje vrátit Hildiřinu {chest} truhlu ({boss})",
    "de": "Erfordert, Hildirs {chest} Truhe zurückzugeben ({boss})",
    "es": "Requiere devolver el cofre de {chest} de Hildir ({boss})",
    "fr": "Nécessite de rapporter le coffre {chest} de Hildir ({boss})",
    "pt": "Requer devolver o baú {chest} de Hildir ({boss})",
    "zh": "需要归还 Hildir 的{chest}宝箱（{boss}）",
    "hi": "Hildir का {chest} संदूक लौटाना आवश्यक है ({boss})",
    "ar": "يتطلب إعادة صندوق هيلدير {chest} ({boss})",
    "bn": "Hildir-এর {chest} সিন্দুক ফেরত দিতে হবে ({boss})",
    "ru": "Требуется вернуть {chest} сундук Hildir ({boss})",
    "ja": "Hildirの{chest}の宝箱を返す必要があります（{boss}）",
    "id": "Perlu mengembalikan peti {chest} milik Hildir ({boss})"
  },
  "Requires killing {creature}": {
    "en": "Requires killing {creature}",
    "cs": "Vyžaduje zabít: {creature}",
    "de": "Erfordert, {creature} zu töten",
    "es": "Requiere matar a {creature}",
    "fr": "Nécessite de tuer {creature}",
    "pt": "Requer matar {creature}",
    "zh": "需要击杀 {creature}",
    "hi": "{creature} को मारना आवश्यक है",
    "ar": "يتطلب قتل {creature}",
    "bn": "{creature} কে হত্যা করতে হবে",
    "ru": "Требуется убить: {creature}",
    "ja": "{creature}を倒す必要があります",
    "id": "Perlu membunuh {creature}"
  },
  "Hildir chest: silver": {
    "en": "silver",
    "cs": "stříbrnou",
    "de": "silberne",
    "es": "plata",
    "fr": "en argent",
    "pt": "de prata",
    "zh": "银",
    "hi": "चाँदी वाला",
    "ar": "الفضي",
    "bn": "রুপার",
    "ru": "серебряный",
    "ja": "銀",
    "id": "perak"
  },
  "Hildir chest: bronze": {
    "en": "bronze",
    "cs": "bronzovou",
    "de": "bronzene",
    "es": "bronce",
    "fr": "en bronze",
    "pt": "de bronze",
    "zh": "青铜",
    "hi": "कांसे वाला",
    "ar": "البرونزي",
    "bn": "ব্রোঞ্জের",
    "ru": "бронзовый",
    "ja": "青銅",
    "id": "perunggu"
  },
  "Hildir chest: brass": {
    "en": "brass",
    "cs": "mosaznou",
    "de": "messingene",
    "es": "latón",
    "fr": "en laiton",
    "pt": "de latão",
    "zh": "黄铜",
    "hi": "पीतल वाला",
    "ar": "النحاسي",
    "bn": "পিতলের",
    "ru": "латунный",
    "ja": "真鍮",
    "id": "kuningan"
  }
};
